<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_inc</name>
   <tag></tag>
   <elementGuidId>6767b8a0-f165-4045-b27e-1b56ff45dca7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.addon-2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
