<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_check_old_price</name>
   <tag></tag>
   <elementGuidId>764ab483-f7c2-47a8-aba3-0c09f46e9fc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cart-first-amount</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
