<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_check_sale_amount</name>
   <tag></tag>
   <elementGuidId>79bb7b64-7f38-4e61-ab51-a07bca96063a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cart-discount-amount</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
