<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_check_new_price</name>
   <tag></tag>
   <elementGuidId>32f2117b-cd71-481f-b955-eb1116c921df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cart-cost</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
