<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_option_type</name>
   <tag></tag>
   <elementGuidId>80515cb8-9356-428a-9fd1-25414b085dde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[text()='Тип']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>//*[text()='Тип']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
