<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_apply</name>
   <tag></tag>
   <elementGuidId>99dd62d0-a45c-442d-88cf-0f97e39b4650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-filter-apply</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
