<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drop_shop_list</name>
   <tag></tag>
   <elementGuidId>a9e31d81-617d-4550-889d-f0b68249f7a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-OneClickOrderForm_shopCode-container</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
