<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_phone</name>
   <tag></tag>
   <elementGuidId>0bca43d6-af66-4d10-8a3f-0de4b8ad337d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OneClickOrderForm_phone</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
