<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_name</name>
   <tag></tag>
   <elementGuidId>81e5af29-c729-49ae-864b-580c9c6cc6a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OneClickOrderForm_name</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
