<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_sorting</name>
   <tag></tag>
   <elementGuidId>6cb3b581-9a81-4363-b393-d0efa21523f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.catalog-sort</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
