<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_pay</name>
   <tag></tag>
   <elementGuidId>3707eb4d-eb08-4d84-82f7-ea0c58b64c41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn-md</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
