<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email</name>
   <tag></tag>
   <elementGuidId>96c711bd-6c49-4927-8eb5-6825a9dbed5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GiftCertificateForm_sender_email</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
