<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_name</name>
   <tag></tag>
   <elementGuidId>abd612a0-3d06-4bd6-9c80-ce0742d0e3d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GiftCertificateForm_sender_name</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
