<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_order_confirm</name>
   <tag></tag>
   <elementGuidId>8787309e-fcc4-42a3-afc9-264821e610ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-order-confirm</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
