<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_appstore</name>
   <tag></tag>
   <elementGuidId>9a564561-8dfa-40ec-81ba-e5be80a065f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.app-header__title</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
