<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_booking</name>
   <tag></tag>
   <elementGuidId>0404cd3c-abf7-4807-940c-933d76b4da9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.js-booking-button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
