<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_order_by_click</name>
   <tag></tag>
   <elementGuidId>a0784faa-afcc-4f28-a894-91337f0ef253</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.item-one-click-link</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
