<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_exit_adv</name>
   <tag></tag>
   <elementGuidId>be3d8bbc-1427-4bc5-a80f-740b63b0e932</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cross</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
