<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_size</name>
   <tag></tag>
   <elementGuidId>ec14b94d-2c06-4f0c-954b-96987c8a7060</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.bootbox-body</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
