<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_region</name>
   <tag></tag>
   <elementGuidId>156f5ed1-7b5d-4b00-8425-04fcd714806d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.region__name-selected</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
